#Build node image from Node Docker Hub
FROM node:alpine3.10

#Make app directory in container
RUN mkdir /nodeapp

#Identify working directory
WORKDIR /nodeapp

#Copy package
COPY package.json /nodeapp

#Install rpm packages from package.json
RUN npm install

#Copy over app to app folder
COPY . /nodeapp/ 

#Expose server at port ( accessible outside of container)
EXPOSE 8080 

#Start app 
CMD ["node", "server.js"]